---
title: "Using and adding IAMC data checks"
author: "Jan Philipp Dietrich"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Using and adding IAMC data checks}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Purpose and Functionality

The iamc R package is a collection of R tools provided by the Integrated Assessment Modeling Consortium (IAMC) for data analysis and diagnostics. It can be used to make sure that a data set is in line with rules set by a given project. This rules can be for instance a given naming convention or unit conventions for variables, but also qualitative measures such as that certain variables lie between certain bounds. Besides that the data can be compared to given validation data.


## A simple example

The package comes with small example data set `example_landcover` which contains some land cover data calculated in the CDLINKS project. To show the functionality of the package some mistakes have been introduced into the data set. To find these mistakes you can feed the object to the check function `iamCheck`

```{r, echo=TRUE}
library(iamc)
iamCheck(example_landcover)
```

This returns information about the checks performed and the problems found in the data.

## Adding own checks

...



