name: check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          extra-repositories: "https://rse.pik-potsdam.de/r/packages"

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::lucode2
            any::covr
            any::madrat
            any::magclass
            any::citation
            any::gms
            any::goxygen
            any::GDPuc
          # piam packages also available on CRAN (madrat, magclass, citation,
          # gms, goxygen, GDPuc) will usually have an outdated binary version
          # available; by using extra-packages we get the newest version

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install python dependencies if applicable
        run: |
          [ -f requirements.txt ] && python -m pip install --upgrade pip wheel || true
          [ -f requirements.txt ] && pip install -r requirements.txt || true

      - name: Verify validation key
        shell: Rscript {0}
        run: lucode2:::validkey(stopIfInvalid = TRUE)

      - name: Checks
        shell: Rscript {0}
        run: |
          options(crayon.enabled = TRUE)
          lucode2::check(runLinter = FALSE)

      - name: Test coverage
        shell: Rscript {0}
        run: covr::codecov(quiet = FALSE)
        env:
          NOT_CRAN: "true"
